import { motion } from 'framer-motion';
import { Bell, ChevronDown, Menu, Search, Sparkles, Star, Sun, Trophy, Users, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Logo } from '../components/brand/Logo.jsx';
import { Button } from '../components/ui/Button.jsx';

const games = ['Valorant', 'Counter-Strike 2', 'League of Legends', 'Fortnite', 'Apex Legends', 'Rocket League', 'Rainbow Six Siege', 'Overwatch 2', 'Marvel Rivals', 'Call of Duty', 'PUBG', 'Chess'];
const leaderboard = ['NeonBlade', 'PhantomX', 'CrystalQueen', 'VoidWalker', 'IronFist'];
const news = ['Valorant Episode 8 Act 3: New Agent Vyse Revealed', 'CS2 Premier Mode Gets Major Update With New Anti-Cheat', 'Fortnite Chapter 6 Season 3 Battle Pass Leaked', 'Valorant Champions 2026 Teams Announced'];

export function LandingPage() {
  return <div className="relative min-h-screen overflow-hidden bg-[#03050a] text-white"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(118,87,255,0.18),transparent_35%),radial-gradient(circle_at_20%_18%,rgba(22,217,255,0.12),transparent_28%)]" /><div className="pointer-events-none absolute inset-0 stars" /><Header /><main className="relative mx-auto grid max-w-[1440px] grid-cols-1 gap-6 px-4 pb-16 pt-20 lg:grid-cols-[250px_1fr_260px] lg:px-8"><LeftRail /><section className="min-w-0"><Hero /><FeatureCard /><PremiumBanner /><GamesGrid /></section><RightRail /></main></div>;
}

function Header() { return <header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#05070d]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-4 lg:px-8"><Logo /><nav className="hidden items-center gap-2 md:flex">{['Home', 'Games', 'Player Card', 'News', 'About Us', 'Support'].map((item, index) => <a className={'rounded-lg px-4 py-2 text-sm font-bold transition ' + (index === 0 ? 'border border-cyan/30 bg-cyan/10 text-cyan' : 'text-slate-400 hover:text-white')} href="#" key={item}>{item}</a>)}</nav><div className="flex items-center gap-2">{[Search, Bell, Sun].map((Icon, index) => <button className="grid h-10 w-10 place-items-center rounded-lg border border-white/10 bg-white/5 text-slate-300" key={index}><Icon size={17} /></button>)}<Link className="hidden items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm font-bold md:flex" to="/register"><span className="grid h-6 w-6 place-items-center rounded-md bg-gradient-to-br from-cyan to-violet"><Users size={14} /></span> ProGamer <ChevronDown size={14} /></Link><button className="grid h-10 w-10 place-items-center rounded-lg border border-white/10 bg-white/5"><Menu size={18} /></button></div></div></header>; }
function Hero() { return <section className="mx-auto max-w-3xl pt-14 text-center"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="inline-flex items-center gap-2 rounded-full border border-cyan/30 bg-cyan/10 px-4 py-2 text-xs font-black uppercase tracking-widest text-cyan"><span className="h-2 w-2 rounded-full bg-cyan" /> The ultimate gaming analytics platform</motion.div><motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }} className="mt-8 bg-gradient-to-r from-cyan via-[#17c6ff] to-violet bg-clip-text font-display text-5xl font-black leading-none text-transparent md:text-7xl">Track. Analyze. Dominate.</motion.h1><p className="mx-auto mt-6 max-w-xl text-lg font-semibold leading-8 text-slate-400">The ultimate premium platform for tracking performance across multiple games. Powered by AI.</p><div className="mx-auto mt-10 flex max-w-2xl overflow-hidden rounded-2xl border border-white/10 bg-white/5 text-left shadow-2xl"><button className="flex min-w-36 items-center justify-between border-r border-white/10 px-4 text-sm font-bold text-slate-300">Valorant <ChevronDown size={16} /></button><input className="min-w-0 flex-1 bg-transparent px-5 text-sm font-semibold text-white outline-none placeholder:text-slate-600" placeholder="Search any player by username..." /><Button className="rounded-l-none"><Search size={16} /> Search</Button></div><div className="mt-8 flex flex-wrap justify-center gap-3"><Button><Zap size={16} /> Create Player Card</Button><Button variant="ghost">Explore Games</Button></div><div className="mt-12 grid grid-cols-2 gap-6 md:grid-cols-4">{[['2.4M+', 'Players Tracked'], ['12', 'Games Supported'], ['98M+', 'Matches Analyzed'], ['4.9', 'User Rating']].map(([value, label]) => <div key={label}><p className="font-display text-2xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>)}</div></section>; }
function FeatureCard() { return <section className="mt-20 rounded-2xl border border-violet/30 bg-gradient-to-br from-violet/15 to-cyan/5 p-8"><div className="inline-flex rounded-full border border-violet/40 bg-violet/15 px-3 py-1 text-xs font-black uppercase text-violet-200">Flagship Feature</div><h2 className="mt-6 font-display text-3xl font-black">Create Your Player Card</h2><p className="mt-4 max-w-xl leading-7 text-slate-300">Upload your photo, connect game accounts, and generate an AI-powered esports identity card with your unique Gamer Score.</p><div className="mt-6 flex flex-wrap gap-3"><Button>Create My Card</Button><Button variant="subtle">Game Accounts</Button><Button variant="subtle">Share Card</Button></div></section>; }
function PremiumBanner() { return <section className="mt-6 rounded-2xl bg-gradient-to-r from-emerald-950 to-emerald-500/80 p-8"><div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-black"><Sparkles size={14} /> New Feature</div><h2 className="mt-6 font-display text-3xl font-black">GameTracker Premium 2.0</h2><p className="mt-3 text-emerald-50">Advanced AI insights now available. Unlock predictive analytics, coaching tools, and VOD review features.</p><Button variant="ghost" className="mt-7">Upgrade Now</Button></section>; }
function GamesGrid() { return <section className="mt-10"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-black"><Trophy size={18} className="text-violet" /> All Games</h2><a className="text-sm font-bold text-cyan" href="#">View All</a></div><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{games.map((game, index) => <article className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 text-center transition hover:-translate-y-1 hover:border-cyan/40" key={game}><div className="text-4xl">{['🔫','🔥','🏹','🏁','🤖','⚽','💣','🧑‍🚀','⚡','🟩','🏝️','🏆'][index]}</div><h3 className="mt-5 font-black">{game}</h3><p className="mt-2 text-xs font-black text-cyan">{['14.2M','1.1M','152M','350M','100M','75M','50M','35M','10M','100M+','75M','800M'][index]}</p></article>)}</div></section>; }
function LeftRail() { return <aside className="hidden pt-[42rem] lg:block"><h2 className="mb-4 flex items-center gap-2 font-black"><Star size={18} className="text-yellow-300" /> Community</h2><div className="space-y-3">{leaderboard.map((name, index) => <div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.04] p-3" key={name}><span className="text-xs font-black text-slate-500">#{index + 1}</span><div className="grid h-9 w-9 place-items-center rounded-lg bg-slate-800">{index + 1}</div><div><p className="text-sm font-black">{name}</p><p className="text-xs text-slate-500">Valorant</p></div><span className="ml-auto text-xs font-black text-cyan">{(9.8 - index * 0.3).toFixed(1)}k</span></div>)}</div></aside>; }
function RightRail() { return <aside className="hidden pt-[42rem] lg:block"><h2 className="mb-4 font-black">Latest News</h2><div className="space-y-4">{news.map((item, index) => <article className="rounded-xl border border-white/10 bg-white/[0.04] p-4" key={item}><span className="rounded bg-cyan/10 px-2 py-1 text-[10px] font-black uppercase text-cyan">{index === 1 ? 'CS2' : 'Esports'}</span><h3 className="mt-3 text-sm font-black leading-5">{item}</h3><p className="mt-2 text-xs text-slate-500">Jun {20 - index}, 2026</p></article>)}</div><h2 className="mt-8 font-black">Trending</h2><div className="mt-4 flex flex-wrap gap-2">{['#Valorant', '#Champions2026', '#CS2Update', '#FortniteS3', '#ApexS22'].map((tag) => <span className="rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-slate-400" key={tag}>{tag}</span>)}</div></aside>; }
